package com.scu.group8.mailServer.dao;

import com.scu.group8.mailServer.pojo.DraftMail;

public interface DraftMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft_mail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft_mail
     *
     * @mbggenerated
     */
    int insert(DraftMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft_mail
     *
     * @mbggenerated
     */
    int insertSelective(DraftMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft_mail
     *
     * @mbggenerated
     */
    DraftMail selectByPrimaryKey(Integer mailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft_mail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DraftMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draft_mail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DraftMail record);
}