package com.scu.group8.mailServer.dao;

import com.scu.group8.mailServer.pojo.ReceivedMail;

public interface ReceivedMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table received_mail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table received_mail
     *
     * @mbggenerated
     */
    int insert(ReceivedMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table received_mail
     *
     * @mbggenerated
     */
    int insertSelective(ReceivedMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table received_mail
     *
     * @mbggenerated
     */
    ReceivedMail selectByPrimaryKey(Integer mailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table received_mail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReceivedMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table received_mail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReceivedMail record);
}