package com.scu.group8.mailServer.dao;

import com.scu.group8.mailServer.pojo.SentMail;

public interface SentMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sent_mail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sent_mail
     *
     * @mbggenerated
     */
    int insert(SentMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sent_mail
     *
     * @mbggenerated
     */
    int insertSelective(SentMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sent_mail
     *
     * @mbggenerated
     */
    SentMail selectByPrimaryKey(Integer mailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sent_mail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SentMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sent_mail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SentMail record);
}