package com.scu.group8.mailServer.dao;

import com.scu.group8.mailServer.pojo.UserPermission;

public interface UserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission
     *
     * @mbggenerated
     */
    int insert(UserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permission
     *
     * @mbggenerated
     */
    int insertSelective(UserPermission record);
}