package com.scu.group8.mailServer.dao;

import com.scu.group8.mailServer.pojo.UserMail;

public interface UserMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbggenerated
     */
    int insert(UserMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mail
     *
     * @mbggenerated
     */
    int insertSelective(UserMail record);
}