package com.scu.group8.mailServer.pojo;

public class DraftMail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draft_mail.mail_id
     *
     * @mbggenerated
     */
    private Integer mailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draft_mail.owner_id
     *
     * @mbggenerated
     */
    private Integer ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draft_mail.draft_status
     *
     * @mbggenerated
     */
    private Integer draftStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draft_mail.mail_id
     *
     * @return the value of draft_mail.mail_id
     *
     * @mbggenerated
     */
    public Integer getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draft_mail.mail_id
     *
     * @param mailId the value for draft_mail.mail_id
     *
     * @mbggenerated
     */
    public void setMailId(Integer mailId) {
        this.mailId = mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draft_mail.owner_id
     *
     * @return the value of draft_mail.owner_id
     *
     * @mbggenerated
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draft_mail.owner_id
     *
     * @param ownerId the value for draft_mail.owner_id
     *
     * @mbggenerated
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draft_mail.draft_status
     *
     * @return the value of draft_mail.draft_status
     *
     * @mbggenerated
     */
    public Integer getDraftStatus() {
        return draftStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draft_mail.draft_status
     *
     * @param draftStatus the value for draft_mail.draft_status
     *
     * @mbggenerated
     */
    public void setDraftStatus(Integer draftStatus) {
        this.draftStatus = draftStatus;
    }
}