package com.scu.group8.mailServer.pojo;

import java.util.Date;

public class Mail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Mail_id
     *
     * @mbggenerated
     */
    private Integer mailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Mail_state
     *
     * @mbggenerated
     */
    private Integer mailState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Mail_sender_id
     *
     * @mbggenerated
     */
    private Integer mailSenderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Mail_recevier_id
     *
     * @mbggenerated
     */
    private Integer mailRecevierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Mail_title
     *
     * @mbggenerated
     */
    private String mailTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.Mail_content
     *
     * @mbggenerated
     */
    private byte[] mailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Mail_id
     *
     * @return the value of mail.Mail_id
     *
     * @mbggenerated
     */
    public Integer getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Mail_id
     *
     * @param mailId the value for mail.Mail_id
     *
     * @mbggenerated
     */
    public void setMailId(Integer mailId) {
        this.mailId = mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Mail_state
     *
     * @return the value of mail.Mail_state
     *
     * @mbggenerated
     */
    public Integer getMailState() {
        return mailState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Mail_state
     *
     * @param mailState the value for mail.Mail_state
     *
     * @mbggenerated
     */
    public void setMailState(Integer mailState) {
        this.mailState = mailState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Mail_sender_id
     *
     * @return the value of mail.Mail_sender_id
     *
     * @mbggenerated
     */
    public Integer getMailSenderId() {
        return mailSenderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Mail_sender_id
     *
     * @param mailSenderId the value for mail.Mail_sender_id
     *
     * @mbggenerated
     */
    public void setMailSenderId(Integer mailSenderId) {
        this.mailSenderId = mailSenderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Mail_recevier_id
     *
     * @return the value of mail.Mail_recevier_id
     *
     * @mbggenerated
     */
    public Integer getMailRecevierId() {
        return mailRecevierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Mail_recevier_id
     *
     * @param mailRecevierId the value for mail.Mail_recevier_id
     *
     * @mbggenerated
     */
    public void setMailRecevierId(Integer mailRecevierId) {
        this.mailRecevierId = mailRecevierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Mail_title
     *
     * @return the value of mail.Mail_title
     *
     * @mbggenerated
     */
    public String getMailTitle() {
        return mailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Mail_title
     *
     * @param mailTitle the value for mail.Mail_title
     *
     * @mbggenerated
     */
    public void setMailTitle(String mailTitle) {
        this.mailTitle = mailTitle == null ? null : mailTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Create_time
     *
     * @return the value of mail.Create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Create_time
     *
     * @param createTime the value for mail.Create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Update_time
     *
     * @return the value of mail.Update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Update_time
     *
     * @param updateTime the value for mail.Update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.Mail_content
     *
     * @return the value of mail.Mail_content
     *
     * @mbggenerated
     */
    public byte[] getMailContent() {
        return mailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.Mail_content
     *
     * @param mailContent the value for mail.Mail_content
     *
     * @mbggenerated
     */
    public void setMailContent(byte[] mailContent) {
        this.mailContent = mailContent;
    }
}