package com.scu.group8.mailServer.pojo;

import java.util.Date;

public class Mail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.mail_id
     *
     * @mbggenerated
     */
    private Integer mailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.sender_email_address
     *
     * @mbggenerated
     */
    private String senderEmailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.recipient_email_address
     *
     * @mbggenerated
     */
    private String recipientEmailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.mail_title
     *
     * @mbggenerated
     */
    private String mailTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.mail_content
     *
     * @mbggenerated
     */
    private byte[] mailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.mail_id
     *
     * @return the value of mail.mail_id
     *
     * @mbggenerated
     */
    public Integer getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.mail_id
     *
     * @param mailId the value for mail.mail_id
     *
     * @mbggenerated
     */
    public void setMailId(Integer mailId) {
        this.mailId = mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.sender_email_address
     *
     * @return the value of mail.sender_email_address
     *
     * @mbggenerated
     */
    public String getSenderEmailAddress() {
        return senderEmailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.sender_email_address
     *
     * @param senderEmailAddress the value for mail.sender_email_address
     *
     * @mbggenerated
     */
    public void setSenderEmailAddress(String senderEmailAddress) {
        this.senderEmailAddress = senderEmailAddress == null ? null : senderEmailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.recipient_email_address
     *
     * @return the value of mail.recipient_email_address
     *
     * @mbggenerated
     */
    public String getRecipientEmailAddress() {
        return recipientEmailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.recipient_email_address
     *
     * @param recipientEmailAddress the value for mail.recipient_email_address
     *
     * @mbggenerated
     */
    public void setRecipientEmailAddress(String recipientEmailAddress) {
        this.recipientEmailAddress = recipientEmailAddress == null ? null : recipientEmailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.mail_title
     *
     * @return the value of mail.mail_title
     *
     * @mbggenerated
     */
    public String getMailTitle() {
        return mailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.mail_title
     *
     * @param mailTitle the value for mail.mail_title
     *
     * @mbggenerated
     */
    public void setMailTitle(String mailTitle) {
        this.mailTitle = mailTitle == null ? null : mailTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.create_time
     *
     * @return the value of mail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.create_time
     *
     * @param createTime the value for mail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.update_time
     *
     * @return the value of mail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.update_time
     *
     * @param updateTime the value for mail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.is_deleted
     *
     * @return the value of mail.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.is_deleted
     *
     * @param isDeleted the value for mail.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.mail_content
     *
     * @return the value of mail.mail_content
     *
     * @mbggenerated
     */
    public byte[] getMailContent() {
        return mailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.mail_content
     *
     * @param mailContent the value for mail.mail_content
     *
     * @mbggenerated
     */
    public void setMailContent(byte[] mailContent) {
        this.mailContent = mailContent;
    }
}