package com.scu.group8.mailServer.pojo;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.Permission_id
     *
     * @mbggenerated
     */
    private Integer permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.Module_id
     *
     * @mbggenerated
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.Request_path
     *
     * @mbggenerated
     */
    private String requestPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.Permission_id
     *
     * @return the value of permission.Permission_id
     *
     * @mbggenerated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.Permission_id
     *
     * @param permissionId the value for permission.Permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.Module_id
     *
     * @return the value of permission.Module_id
     *
     * @mbggenerated
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.Module_id
     *
     * @param moduleId the value for permission.Module_id
     *
     * @mbggenerated
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.Request_path
     *
     * @return the value of permission.Request_path
     *
     * @mbggenerated
     */
    public String getRequestPath() {
        return requestPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.Request_path
     *
     * @param requestPath the value for permission.Request_path
     *
     * @mbggenerated
     */
    public void setRequestPath(String requestPath) {
        this.requestPath = requestPath == null ? null : requestPath.trim();
    }
}