package com.scu.group8.mailServer.pojo;

public class UserMail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mail.Mail_sender_id
     *
     * @mbggenerated
     */
    private Integer mailSenderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mail.Mail_id
     *
     * @mbggenerated
     */
    private Integer mailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mail.Mail_state
     *
     * @mbggenerated
     */
    private Integer mailState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mail.Mail_sender_id
     *
     * @return the value of user_mail.Mail_sender_id
     *
     * @mbggenerated
     */
    public Integer getMailSenderId() {
        return mailSenderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mail.Mail_sender_id
     *
     * @param mailSenderId the value for user_mail.Mail_sender_id
     *
     * @mbggenerated
     */
    public void setMailSenderId(Integer mailSenderId) {
        this.mailSenderId = mailSenderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mail.Mail_id
     *
     * @return the value of user_mail.Mail_id
     *
     * @mbggenerated
     */
    public Integer getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mail.Mail_id
     *
     * @param mailId the value for user_mail.Mail_id
     *
     * @mbggenerated
     */
    public void setMailId(Integer mailId) {
        this.mailId = mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mail.Mail_state
     *
     * @return the value of user_mail.Mail_state
     *
     * @mbggenerated
     */
    public Integer getMailState() {
        return mailState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mail.Mail_state
     *
     * @param mailState the value for user_mail.Mail_state
     *
     * @mbggenerated
     */
    public void setMailState(Integer mailState) {
        this.mailState = mailState;
    }
}